application: example-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: example-app.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
